### ISSUE TITLE
Missing documentation for events emitted

### ISSUE THREAD

**Issue by juliomatcom** [IonicaBizau/flight-tracker#3]
Hello i think you miss some documentation for events emitted in section
https://github.com/IonicaBizau/flight-tracker/blob/master/DOCUMENTATION.md

> EventEmitter An EventEmitter object emitting the following events:

:facepunch:

**Comment by IonicaBizau** [comment]
@juliomatcom Oh, thanks! Will have that in attention. 👍

**Comment by IonicaBizau** [comment]
Fixed via #4.
